// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220206224617_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Category = "Drama/Romance",
                            Director = "Gus Van Sant",
                            Edited = false,
                            LentTo = "N/A",
                            Notes = "N/A",
                            Rating = "R",
                            Title = "Good Will Hunting",
                            Year = 1997
                        },
                        new
                        {
                            ApplicationId = 2,
                            Category = "Drama/Crime",
                            Director = "Steven Spielberg",
                            Edited = false,
                            LentTo = "N/A",
                            Notes = "N/A",
                            Rating = "PG-13",
                            Title = "Catch Me If You Can",
                            Year = 2002
                        },
                        new
                        {
                            ApplicationId = 3,
                            Category = "Drama",
                            Director = "Grabriele Muccino",
                            Edited = false,
                            LentTo = "Jonah",
                            Notes = "Feel Good Movie",
                            Rating = "PG-13",
                            Title = "The Pursuit of Happyness",
                            Year = 2006
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
